const express = require("express");
const Router = express.Router();
const CartController = require("../controllers/CartController");
const OrderController = require("../controllers/orderController");
const { paramMiddleware } = require('../helper/Convert');
const { verifyAccessToken, addUserToRequest } = require('../services/JwtService');
Router.post("/create-order", paramMiddleware('/cart'), verifyAccessToken, OrderController.createOrderXemart);
Router.post("/applyVoucher", verifyAccessToken, OrderController.applyVoucher);
Router.post("/unApplyVoucher", verifyAccessToken, OrderController.unApplyVoucher);
Router.post("/getAndUpdateCompTotal", verifyAccessToken, OrderController.getAndUpdateCompTotal);
Router.post("/add-product", addUserToRequest, CartController.addToCart);
Router.post("/get-all", CartController.getCart);
Router.post("/delete-cart", CartController.delCart);
module.exports = Router;