const express = require("express");
const Router = express.Router();
const HomeController = require("../controllers/home");
const AdminController = require("../controllers/adminController");
const OrderController = require("../controllers/orderController");
const { checkUserLogin } = require("../middleware/checkUserLogin");
Router.get("/", HomeController.homePage);
Router.get("/detail/:url_path", HomeController.detailPage);
Router.get("/cart", checkUserLogin, HomeController.cartPage);
Router.get("/login", HomeController.loginPage);
Router.get("/blogs", HomeController.blogsPage);
Router.get("/searchProduct", HomeController.searchProduct);
Router.get("/testSocket", HomeController.testSocket);
Router.get("/load_images", AdminController.load_images);
Router.post("/delete_image", AdminController.delete_image);
Router.post("/get-model", HomeController.getModelProduct)
Router.get("/blog-detail/:id", HomeController.blogDetailPage);
Router.get("/checkout/:id", OrderController.checkoutPage);
Router.get("/test-post", HomeController.testpost);
Router.post("/register", HomeController.registerAccount);
Router.post("/create-order", OrderController.createOrder);
Router.post("/login", HomeController.loginAccount);
Router.post("/create_payment_url", HomeController.vnpPayment);
Router.post("/create_payment_MoMo", HomeController.momoPayment);
Router.post("/testmail", HomeController.testSendMail);
Router.post("/dat-hang", OrderController.datHang);
Router.post("/checkout-paypal", OrderController.checkoutPaypal);
Router.get("/vnpay-redirect/:orderId", OrderController.VnPayHandel);
Router.get("/momo-redirect/:orderId", OrderController.MomoHandel);
Router.get("/cat/:cat_path", HomeController.categoryPage);
module.exports = Router;